# -*- coding: utf-8 -*-
"""pyTorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVREtyfTe4RFbdYRRWFfjASBoaOxh-FN
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

r = (torch.zeros(2, 2) + 0.233)
print(r)

tensor1 = torch.tensor(([[1,2,3],[4,5,6],[7,8,9]]), dtype = torch.int64)
tensor1

tensor2 = torch.tensor(([[1.123,2.345,3.456],[1.123,2.345,3.456],[1.123,2.345,3.456]]))
tensor2

print(tensor2[0, 1,])

randomNUM = 42
torch.manual_seed(randomNUM)
random1 = torch.rand(4,3)
torch.manual_seed(randomNUM)
random2 = torch.rand(4,3)

print(random2==random1)

!nvidia-smi

tensor=torch.rand(1,2,device = "cpu")
print(tensor, tensor.device)
tensroGPU = tensor.to("cuda")

tensor=tensor.to("cuda")
print(tensor.device)

coolkids = torch.tensor([[[1],[2],[1]],[[1],[2],[1]],[[1],[2],[1]]])
print(coolkids)